# Generated by Django 3.1.7 on 2021-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
